CREATE TABLE CONTACT (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    NAME VARCHAR2(200) NOT NULL,
    AGE NUMBER(3) NOT NULL CHECK (AGE > 0 AND AGE < 150),
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);

CREATE TABLE PHONE (
    ID NUMBER GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    CONTACT_ID NUMBER NOT NULL,
    PHONE_NUMBER VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
    CONSTRAINT FK_PHONE_CONTACT FOREIGN KEY (CONTACT_ID) 
        REFERENCES CONTACT(ID) ON DELETE CASCADE
);

CREATE INDEX IDX_CONTACT_NAME ON CONTACT(UPPER(NAME));
CREATE INDEX IDX_PHONE_NUMBER ON PHONE(PHONE_NUMBER);
CREATE INDEX IDX_PHONE_CONTACT_ID ON PHONE(CONTACT_ID);
