CREATE OR REPLACE PROCEDURE SP_SEARCH_CONTACTS (
    p_search_term IN VARCHAR2,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    IF p_search_term IS NULL OR TRIM(p_search_term) = '' THEN
        OPEN p_cursor FOR
            SELECT c.ID, c.NAME, c.AGE, c.CREATED_AT, c.UPDATED_AT
            FROM CONTACT c
            ORDER BY c.NAME;
    ELSE
        OPEN p_cursor FOR
            SELECT DISTINCT c.ID, c.NAME, c.AGE, c.CREATED_AT, c.UPDATED_AT
            FROM CONTACT c
            LEFT JOIN PHONE p ON c.ID = p.CONTACT_ID
            WHERE UPPER(c.NAME) LIKE '%' || UPPER(p_search_term) || '%'
               OR p.PHONE_NUMBER LIKE '%' || p_search_term || '%'
            ORDER BY c.NAME;
    END IF;
END SP_SEARCH_CONTACTS;
/

CREATE OR REPLACE PROCEDURE SP_GET_CONTACT_PHONES (
    p_contact_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT ID, CONTACT_ID, PHONE_NUMBER, CREATED_AT
        FROM PHONE
        WHERE CONTACT_ID = p_contact_id
        ORDER BY ID;
END SP_GET_CONTACT_PHONES;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_CONTACT (
    p_name IN VARCHAR2,
    p_age IN NUMBER,
    p_contact_id OUT NUMBER
) AS
BEGIN
    INSERT INTO CONTACT (NAME, AGE)
    VALUES (p_name, p_age)
    RETURNING ID INTO p_contact_id;
END SP_INSERT_CONTACT;
/

CREATE OR REPLACE PROCEDURE SP_INSERT_PHONE (
    p_contact_id IN NUMBER,
    p_phone_number IN VARCHAR2,
    p_phone_id OUT NUMBER
) AS
BEGIN
    INSERT INTO PHONE (CONTACT_ID, PHONE_NUMBER)
    VALUES (p_contact_id, p_phone_number)
    RETURNING ID INTO p_phone_id;
END SP_INSERT_PHONE;
/

CREATE OR REPLACE PROCEDURE SP_UPDATE_CONTACT (
    p_id IN NUMBER,
    p_name IN VARCHAR2,
    p_age IN NUMBER
) AS
BEGIN
    UPDATE CONTACT
    SET NAME = p_name,
        AGE = p_age,
        UPDATED_AT = CURRENT_TIMESTAMP
    WHERE ID = p_id;
END SP_UPDATE_CONTACT;
/

CREATE OR REPLACE PROCEDURE SP_DELETE_CONTACT (
    p_id IN NUMBER,
    p_deleted_name OUT VARCHAR2,
    p_phone_count OUT NUMBER
) AS
BEGIN
    SELECT NAME INTO p_deleted_name FROM CONTACT WHERE ID = p_id;
    SELECT COUNT(*) INTO p_phone_count FROM PHONE WHERE CONTACT_ID = p_id;
    DELETE FROM CONTACT WHERE ID = p_id;
EXCEPTION
    WHEN NO_DATA_FOUND THEN
        p_deleted_name := NULL;
        p_phone_count := 0;
END SP_DELETE_CONTACT;
/

CREATE OR REPLACE PROCEDURE SP_DELETE_PHONES_BY_CONTACT (
    p_contact_id IN NUMBER
) AS
BEGIN
    DELETE FROM PHONE WHERE CONTACT_ID = p_contact_id;
END SP_DELETE_PHONES_BY_CONTACT;
/

CREATE OR REPLACE PROCEDURE SP_GET_CONTACT_BY_ID (
    p_id IN NUMBER,
    p_cursor OUT SYS_REFCURSOR
) AS
BEGIN
    OPEN p_cursor FOR
        SELECT ID, NAME, AGE, CREATED_AT, UPDATED_AT
        FROM CONTACT
        WHERE ID = p_id;
END SP_GET_CONTACT_BY_ID;
/
